import Head from "next/head";
import {isEmpty} from 'lodash';

const SEO = ({font, data}) => {
  const titleSite = data?.siteHeader?.siteTitle;

  if(isEmpty(titleSite)) {
    return null;
  }
  return(
    <>
    <Head>
      <title>
        {titleSite?.title} || {titleSite?.description}
      </title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content="Generated by create next app" />
      <meta name="robots" content="noindex, follow" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <link href={font} rel="stylesheet" />
      <link rel="icon" href={data?.favIcons?.favIcon?.sourceUrl} />
    </Head>
  </>
  );
}

export default SEO;